# Numpy

In [3]:
#numpy provides the array object that is upto 50x faster than traditional list

In [ ]:
"""
--->Faster to read less bytes of memory than python lists
--->Contigous memory 
--->In lists the elements in the memory scattered around and not continous,Each element in the list points to that scattered position
--->Numpy is continous memory(all elements are next to each other)
"""

In [4]:
import numpy as np 

In [8]:
arr = np.array([1,2,3,4,5])

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
#get the numpy version

In [11]:
print(np.__version__)

1.19.2


In [12]:
#-->Numpy is used to work with arrays.The array object in numpy is called ndarray

In [13]:
#-->We can create nd array object using the array() function

In [14]:
print(arr)

[1 2 3 4 5]


In [15]:
print(type(arr))

<class 'numpy.ndarray'>


In [16]:
#-->To create an ndarray,we can pass a list,tuple or any array-like object into the array() method,
#and it will converted into an ndarray

In [17]:
arr=np.array((1,2,3,4,5))

In [18]:
print(arr)

[1 2 3 4 5]


# Dimensions in Array

## 0-D Arrays

In [20]:
import numpy as np

In [23]:
arr=np.array(42)#0D arrays are scalars

In [22]:
print(arr)

42


## 1-D Arrays

In [24]:
arr = np.array([1,2,3,4,5])

In [25]:
#1-D is the sequence of scalers, imagine it as only one x axis

In [26]:
print(arr)

[1 2 3 4 5]


## 2-D Arrays

In [27]:
#An array that has 1-D arrays as its elements is called a 2-D arrays

In [28]:
#They are often used to represent matrix or 2nd order tensors

In [29]:
arr = np.array([[1,2,3],[4,5,6]])

In [30]:
print(arr)

[[1 2 3]
 [4 5 6]]


## 3-D Arrays

In [31]:
#An array that has 2-D arrays(matrices) as its elements is called 3-D array

In [32]:
import numpy as np

In [33]:
arr =np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [34]:
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check the Dimension

In [36]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [39]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimension Arrays

In [40]:
#An array can have any number of dimensions

In [41]:
#When tharray is created,you can define the number of dimensions by using the ndmin argument

In [42]:
arr = np.array([1,2,3,4],ndmin=5)

In [43]:
print(arr)
print("number of dimensions:",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


# The Basics

In [45]:
a=np.array([1,2,3])

In [47]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [48]:
#Get dimension

In [49]:
a.ndim

1

In [50]:
b.ndim

2

In [51]:
#indexing 

In [53]:
#Array indexing is te same as accessing an array element
#Array index start from 0

In [54]:
print(a[0])

1


In [56]:
print(a[1])

2


In [59]:
print(a[1] + a[2])

5


In [60]:
#Accesss2-D arrays

In [61]:
print(0,1)#

0 1


In [62]:
#access 3nd element on 1st dimension

In [63]:
print(1,2)

1 2


In [64]:
#Access 3-D arrays

In [65]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [66]:
print(arr[0,1,2])

6


In [67]:
#Negative indexing

In [68]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [69]:
print(arr[1,-1])#access from end

10


# Slicing


In [70]:
#We can pass slice instead if index like [start:end]
#we can also define the step like [start:end:step]

In [71]:
arr=np.array([1,2,3,4,5,6,7])

In [73]:
arr[1:5]#upto not including

array([2, 3, 4, 5])

In [75]:
arr[4:]#from index4 to everything

array([5, 6, 7])

In [76]:
arr[:4]#slice from begenning to index4

array([1, 2, 3, 4])

In [77]:
#Negetive slicing

In [78]:
print(arr[-3:-1])#from (-3+len(arr)) to (-1+len(arr)) index

[5 6]


In [79]:
#step

In [80]:
print(arr[1:5:2])#from index 1 to upto5 with two steps

[2 4]


# Slicing 2-D Arrays

In [81]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [82]:
print(arr[1,1:4])#selecting 1 in first dimension and selecting elements indexed from 1 to upto 4

[7 8 9]


In [83]:
print(arr[0:2,2])#slecting 0 to upto 2 nd index and returing 2 nd indexed element from 2d array

[3 8]


In [84]:
#slicing from both dimensions

In [85]:
print(arr[0:2,1:3])

[[2 3]
 [7 8]]


# Checking the Data Type

In [86]:
print(arr.dtype)

int32


In [87]:
arr2=np.array(["apple","banana","cherry"])

In [88]:
print(arr2.dtype)

<U6


In [89]:
#creating arrays with defined data type

In [90]:
arr3=np.array([1,2,3,4],dtype="S")

In [91]:
print(arr3)

[b'1' b'2' b'3' b'4']


In [92]:
arr4=np.array([1,2,3,4],dtype="i4")#with 4 bytes integer

In [93]:
arr4

array([1, 2, 3, 4])

# Converting Data Types On Existing Arrays

In [94]:
#The best way to change the data type of an existing array is to make copy of an array with astype() method

In [95]:
#The astype() function crreates a copy of the array and allows you to specify the data type

In [96]:
arr =np.array([1.1,2.1,3.1])

In [97]:
newarr=arr.astype("i")

In [98]:
print(arr)

[1.1 2.1 3.1]


In [99]:
print(newarr)

[1 2 3]


In [100]:
print(arr.dtype,newarr.dtype)

float64 int32


In [101]:
#you can use int parameter value

In [103]:
newarr1=arr.astype(int)

In [104]:
print(newarr1)

[1 2 3]


In [105]:
#Change the data type from integer to boolean 

In [106]:
arr=np.array([1,0,3])

In [107]:
newarr=arr.astype(bool)

In [109]:
print(newarr)#if value is >0 then its true either false

[ True False  True]


# Difference between Copy and View

In [110]:
"""
The main difference between copy and view id 
-->copy creates the new array
-->view just views the original array
-->The copy owns the data and any changes made to copy will not affect the original data
and any changes made to original data doesnt effect the copy 
-->The view does not own the data any changes made to view will effect the original one

"""


'\nThe main difference between copy and view id \n-->copy creates the new array\n-->view just views the original array\n-->The copy owns the data and any changes made to copy will not affect the original data\nand any changes made to original data doesnt effect the copy \n-->The view does not own the data any changes made to view will effect the original one\n\n'

In [118]:
#copy
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)
print(x.base)#what is the base of the object x

[42  2  3  4  5]
[1 2 3 4 5]
None


In [117]:
#view
arr1=np.array([1,2,3,4,5])
x=arr1.view()
arr1[0]=42

print(arr1)
print(x)
#make changes
x[1]=8
print(arr1,x)
print(x.base)#what is the base of this object x

[42  2  3  4  5]
[42  2  3  4  5]
[42  8  3  4  5] [42  8  3  4  5]
[42  8  3  4  5]


In [116]:
#to check if array owns the data 
#Every numpy array has the attribute base that returns None if the array owns the data
#otherwise base attribute refers to the original object

# Shape

In [119]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)#The array has 2 dimensions and each dimension has 4 elements 

(2, 4)


In [120]:
#create the array with 5 dimensions using ndim using vector with values 1,2,3,4

In [122]:
arr=np.array([1,2,3,4],ndmin=5)

In [123]:
print(arr)

[[[[[1 2 3 4]]]]]


In [124]:
arr.shape

(1, 1, 1, 1, 4)

In [126]:
arr=np.array([1,2,3,4,5],ndmin=3)

In [127]:
arr.shape

(1, 1, 5)

In [128]:
print(arr)

[[[1 2 3 4 5]]]


In [132]:
arr=np.array([[[1,2,3,4,5,6],[4,5,6,7,8,9]],[[1,2,3,4,5,6],[4,5,6,7,8,9]],[[1,2,3,4,5,6],[4,5,6,7,8,9]]])

In [133]:
print(arr)

[[[1 2 3 4 5 6]
  [4 5 6 7 8 9]]

 [[1 2 3 4 5 6]
  [4 5 6 7 8 9]]

 [[1 2 3 4 5 6]
  [4 5 6 7 8 9]]]


In [134]:
arr.shape

(3, 2, 6)

In [135]:
"""
-->axis-0 value is 3 means we have three 2 dimensional arrays(or someboddy will consider it as 1 st dimension has 3 elements) 
-->axis-1 value is 2 means we have Two 1 dimensional arrays inside each 2 dimension
-->axis-2 value is 6 means we have 6 elements(or six 0 dimensions) in those one dimensional array
"""

'\n-->axis-0 value is 3 means we have three 2 dimensional arrays \n-->axis-1 value is 2 means we have Two 1 dimensional arrays inside each 2 dimension\n-->axis-2 value is 6 means we have 6 elements in those one dimensional array\n'

# Reshaping Arrays

In [136]:
#Reshaping means chaning the shape of an array
#The shape of an array is the numberr of elements in each dimension
#By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [137]:
#Reshape from 1-D to 2-D

In [141]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [142]:
newarr=arr.reshape(4,3)#saying that we want 2 dimensional space whish contains 4 1 dimensional embeded with 3 0 dimensiona;

In [143]:
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [144]:
#Reshape from 1-D to 3-D

In [145]:
newarr1=arr.reshape(2,3,2)#we want 3 dimensional space with contains two 2 dimensional embeded with threee 1 dimensional and further embeded with 2 o dimensional

In [146]:
print(newarr1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [148]:
print(newarr1.base)#so its view

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [149]:
#Unknown Dimension

In [150]:
#you are allowed to have one "Unknown" dimension
#Meaning that you do not have to specify an exact number for one of the dimension in the reshape method
#pass -1 as the value,and the numpy will calculate for you

In [151]:
arr=np.array([1,2,3,4,5,6,7,8])

In [152]:
newarr=arr.reshape(2,2,-1)

In [153]:
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays 

In [154]:
#Flattening array means converting a multidimensional array into a 1D array

In [155]:
#we can use reshape(-1) to dothis

In [156]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [157]:
newarr=arr.reshape(-1)

In [158]:
print(newarr)

[1 2 3 4 5 6]


# Iterating Arrays

In [159]:
#iterating means going throough elements oone by one

In [160]:
#Example

In [161]:
arr=np.array([1,2,3])

In [162]:
for i in arr:
    print(i)

1
2
3


In [163]:
#iterating 2d arrays

In [164]:
arr=np.array([[1,2,3],[4,5,6]])

In [165]:
for x in arr:
    print(x)#iterate through 1 dimensional in the 2 dimensional

[1 2 3]
[4 5 6]


In [166]:
#if w go through n dimensional it will go through n-1th dimensional one by one

In [167]:
for x in arr:
    for y in x:
        print(y)#getting 0 dimensional from 2 dimesional
        #2-0 is 2,so we need 2 for loops to iterate through it

1
2
3
4
5
6


In [168]:
#iterating through 3d arrays

In [169]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [170]:
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [171]:
#3-0 is 3,so we need 3 for loops to get  0 dimensions

In [172]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays using nditer()

In [173]:
#Iterating on each scaler elements 

In [174]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [176]:
arr.shape

(2, 2, 2)

In [177]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


# Iterating Array  with Different Data types

In [178]:
#we can use "op_dtypes" argument and pass it the expected datatype to change the datatype of elements while iterating

In [179]:
"""
-->NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

"""

"\n-->NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].\n\n"

In [180]:
arr =np.array([1,2,3])

In [183]:
for x in np.nditer(arr,flags=["buffered"],op_dtypes=["S"]):
    print(x)#change the data types of the elements while iterating

b'1'
b'2'
b'3'


In [182]:
arr

array([1, 2, 3])

In [184]:
#iterating with different step size

In [185]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [186]:
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [187]:
#enumerated iteration

In [188]:
arr = np.array([1, 2, 3])

In [189]:
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [190]:
#Enumerate on following 2D array's elements:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [191]:
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Numpy Joining Array

In [193]:
#joining means putting the contents of two or more arrays in a single array

In [194]:
#In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

In [195]:
#We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [200]:
arr1=np.array([1, 2, 3])

In [201]:
arr2=np.array([4, 5, 6])

In [202]:
arr=np.concatenate((arr1,arr2))

In [204]:
print(arr)#joined two arrays with one array

[1 2 3 4 5 6]


In [205]:
#join the 2-D arrays along rows(axis=1):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr=np.concatenate((arr1,arr2),axis=1)

In [206]:
print(arr)#2x4

[[1 2 5 6]
 [3 4 7 8]]


In [207]:
arr3=np.concatenate((arr1,arr2),axis=0)

In [208]:
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Joining Arrays Using Stack Functions

In [209]:
#Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [210]:
#We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

In [211]:
#We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [212]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [213]:
arr=np.stack((arr1,arr2),axis=1)

In [214]:
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [215]:
arrc=np.concatenate((arr1,arr2),axis=0)

In [216]:
print(arrc)

[1 2 3 4 5 6]


In [217]:
arr=np.stack((arr1,arr2),axis=0)

In [218]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [219]:
#python provides helper function hstack() to stak along rows

In [4]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [9]:
arr=np.hstack((arr1,arr2))

In [10]:
print(arr)

[1 2 3 4 5 6]


In [12]:
arrv=np.vstack((arr1,arr2))

In [13]:
print(arrv)

[[1 2 3]
 [4 5 6]]


In [14]:
arrd=np.dstack((arr1,arr2))

In [15]:
print(arrd)

[[[1 4]
  [2 5]
  [3 6]]]


In [11]:
arr.shape

(6,)

In [16]:
arrv.shape

(2, 3)

In [17]:
arrd.shape

(1, 3, 2)

In [18]:
#in case of dstack it added new axis2

# Splitting Numpy Arrays

In [20]:
#Splitting is the reverse operation of joining

In [21]:
#Joining merges multiple arrays into one Splitting breaks one array into mutiple

In [22]:
#Example

In [31]:
arr=np.array([1,2,3,4,5,6])

In [32]:
newarr=np.array_split(arr,3)

In [33]:
print(newarr)#split the array into three arrays

[array([1, 2]), array([3, 4]), array([5, 6])]


In [34]:
#if the array has less elements than required it will adjust from the end accordingly

In [35]:
arr=np.array([1,2,3,4,5,6])

In [36]:
newarr1=np.array_split(arr,4)

In [37]:
print(newarr1)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [38]:
print(newarr[0])

[1 2]


In [39]:
print(newarr[2])

[5 6]


In [40]:
#splitting 2d arrays

In [41]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

In [46]:
newarr2=np.array_split(arr,3,axis=1)

In [47]:
print(newarr2)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

In [49]:
newarr3=np.hsplit(arr,3)

In [51]:
newarr3

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

# Searching Arrays

In [52]:
#You can search an array for a certain value,and return the indexes that get a match.

In [53]:
#to search we use where() method

In [54]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [55]:
x=np.where(arr == 4)

In [57]:
print(x)#returns the indeces that get match

(array([3, 5, 6], dtype=int64),)


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
x=np.where(arr%2 == 0)

In [61]:
print(x)#returns the indeces which satisfy the condition

(array([1, 3, 5, 7], dtype=int64),)


In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
x=np.where(arr%2 == 1)

In [64]:
print(x)

(array([0, 2, 4, 6], dtype=int64),)


# Sorting Arrays

In [65]:
#sorting means putting elements in ordered sequence

In [66]:
arr = np.array([3, 2, 0, 1])

In [67]:
print(np.sort(arr))

[0 1 2 3]


In [68]:
arr1=np.array(["banana","cherry","apple"])

In [69]:
print(np.sort(arr))

[0 1 2 3]


In [70]:
#sort a boolean array

In [72]:
arr2=np.array([True,False,True])

In [73]:
print(arr2)

[ True False  True]


In [74]:
#Sorting a 2D array

In [75]:
arr3=np.array([[3,2,4],[5,0,1]])

In [77]:
print(np.sort(arr3))#sorts for each dimension

[[2 3 4]
 [0 1 5]]


# Filtering Arrays

In [78]:
#Getting some elements out of an existing array and creating a new array out of them is caleed filtering

In [79]:
#In numpy you filter an array using an boolean index list

In [80]:
"""
-->if the index is true that element is contained in the filtered array
-->if the element is false that element is excluded from the filterred array
"""
arr=np.array([41,42,43,44])

In [81]:
x=[True,False,True,False]

In [82]:
newarr=arr[x]

In [83]:
print(newarr)

[41 43]


In [84]:
#Example

In [86]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [87]:
#creating the filtered array directly  from the array

In [88]:
arr=np.array([41,42,43,44])

In [89]:
filter_arr =arr>42

In [90]:
newarr=arr[filter_arr]

In [91]:
print(newarr)

[43 44]


# Random Numbers

In [1]:
#numpy offers the random module to work with random numbers

In [2]:
from numpy import random

In [3]:
x=random.randint(100)

In [4]:
x

19

In [5]:
x

19

In [7]:
print(x)

19


In [8]:
#Generate random float

In [9]:
z=random.rand() # Generate random float 0 to 1

In [10]:
print(z)

0.1215020921696971


In [11]:
#Generate Random Array

In [12]:
#Intergers

In [13]:
#The randint() method takes a size parameter where you cn specify the shape of an array

In [16]:
x=random.randint(100,size=(5))#create random integers up to 100 with size 51

In [17]:
print(x)

[50 85 81 73 60]


In [18]:
#Generate a 2-D array with 3 rows ,each row containg 5 Random integers from 0to 100

In [19]:
from numpy import random 

In [20]:
x=random.randint(100,size=(3,5))

In [21]:
print(x)

[[34 97 70 58 83]
 [ 9 31 36 52 63]
 [69 18 63 86 37]]


In [22]:
#Floats 

In [23]:
#The rand() method also allows you to specify the shape of the array 

In [24]:
from numpy import random

In [25]:
x=random.rand(5)

In [26]:
print(x)

[0.77443528 0.09888852 0.06838777 0.77752748 0.92912279]


In [27]:
#Generate a 2-D array with 3 rows,each row containing 5 random numbers

In [28]:
from numpy import random

In [29]:
x=random.rand(3,5)

In [30]:
print(x)

[[0.39976756 0.88422244 0.79132636 0.59554916 0.51654788]
 [0.53237659 0.60720652 0.6211637  0.3560653  0.24221919]
 [0.31954099 0.53824894 0.742828   0.23814534 0.81281199]]


# Generate random number for the array

In [31]:
#The Choice() method allows you to generate a random value based on an array of values

In [33]:
#The Choice() methods takes an array as a parameter and randomly returns one of the values

In [37]:
x=random.choice([3,5,7,9])#generate a random number from this array

In [36]:
print(x)

3


In [38]:
#The choice()  method also allows you to return an array of values

In [39]:
#Add a size parameter to specify the shape of the array

In [40]:
x=random.choice([3,5,7,9],size=(3,5))

In [41]:
print(x)

[[3 9 5 3 9]
 [5 3 3 9 5]
 [3 9 9 5 3]]


In [42]:
#numpy.random.randn()-->function creates an array of specified shape and fills it with random values as per standerd normal distribution

In [43]:
#numpy.random.randn(d0, d1, ..., dn)

In [44]:
#d0, d1, ..., dn : [int, optional]Dimension of the returned array we require, 
 #    If no argument is given a single Python float is returned.

In [48]:
array=random.randn()#randoms numbers which are normally distributed

In [49]:
print(array)

-0.02570223622603511


In [50]:
array=random.randn(5)

In [51]:
print(array)

[ 0.04324242 -0.19854695  0.49936637  0.40732503  0.78944206]


In [52]:
#randomly constructing 2D array

In [53]:
array=random.randn(3,4)

In [54]:
print(array)

[[-0.58828089 -1.22069261 -1.95079476  0.22864626]
 [ 2.68044713  1.4084357  -0.0747251   0.94664405]
 [-1.3686041   0.52293291 -0.38238446 -2.42818518]]


In [55]:
#randomly constructing 3D array

In [56]:
array=random.randn(2,2,2)

In [57]:
print(array)

[[[-1.35359377 -0.75730028]
  [-0.06004178  0.71217268]]

 [[-1.38421962  1.09025081]
  [-1.25374883 -0.23513379]]]


# numpy.arrange()

In [1]:
#it creates an array by using the evenly spaced values over the given interval.The interval mentioned is half opened [start,stop]

In [2]:
"""
1.start-->The starting of an interval.The default is 0.
2.stop-->Represents the value at which the interval ends excluding this value
3.step-->The number by which the interval values change.
4.dtype-->the data type of the numpy array items
"""

'\n1.start-->The starting of an interval.The default is 0.\n2.stop-->Represents the value at which the interval ends excluding this value\n3.step-->The number by which the interval values change.\n4.dtype-->the data type of the numpy array items\n'

In [5]:
arr=np.arange(0,10,2,float)

In [6]:
print(arr)

[0. 2. 4. 6. 8.]


In [7]:
arr1=np.arange(10,100,5,int)

In [8]:
print(arr1)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
