# Numpy

In [3]:
#numpy provides the array object that is upto 50x faster than traditional list

In [ ]:
"""
--->Faster to read less bytes of memory than python lists
--->Contigous memory 
--->In lists the elements in the memory scattered around and not continous,Each element in the list points to that scattered position
--->Numpy is continous memory(all elements are next to each other)
"""

In [7]:
import numpy as np 

In [8]:
arr = np.array([1,2,3,4,5])

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
#get the numpy version

In [11]:
print(np.__version__)

1.19.2


In [12]:
#-->Numpy is used to work with arrays.The array object in numpy is called ndarray

In [13]:
#-->We can create nd array object using the array() function

In [14]:
print(arr)

[1 2 3 4 5]


In [15]:
print(type(arr))

<class 'numpy.ndarray'>


In [16]:
#-->To create an ndarray,we can pass a list,tuple or any array-like object into the array() method,
#and it will converted into an ndarray

In [17]:
arr=np.array((1,2,3,4,5))

In [18]:
print(arr)

[1 2 3 4 5]


# Dimensions in Array

## 0-D Arrays

In [20]:
import numpy as np

In [23]:
arr=np.array(42)#0D arrays are scalars

In [22]:
print(arr)

42


## 1-D Arrays

In [24]:
arr = np.array([1,2,3,4,5])

In [25]:
#1-D is the sequence of scalers, imagine it as only one x axis

In [26]:
print(arr)

[1 2 3 4 5]


## 2-D Arrays

In [27]:
#An array that has 1-D arrays as its elements is called a 2-D arrays

In [28]:
#They are often used to represent matrix or 2nd order tensors

In [29]:
arr = np.array([[1,2,3],[4,5,6]])

In [30]:
print(arr)

[[1 2 3]
 [4 5 6]]


## 3-D Arrays

In [31]:
#An array that has 2-D arrays(matrices) as its elements is called 3-D array

In [32]:
import numpy as np

In [33]:
arr =np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [34]:
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check the Dimension

In [36]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [39]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimension Arrays

In [40]:
#An array can have any number of dimensions

In [41]:
#When tharray is created,you can define the number of dimensions by using the ndmin argument

In [42]:
arr = np.array([1,2,3,4],ndmin=5)

In [43]:
print(arr)
print("number of dimensions:",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


# The Basics

In [45]:
a=np.array([1,2,3])

In [47]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [48]:
#Get dimension

In [49]:
a.ndim

1

In [50]:
b.ndim

2

In [51]:
#indexing 

In [53]:
#Array indexing is te same as accessing an array element
#Array index start from 0

In [54]:
print(a[0])

1


In [56]:
print(a[1])

2


In [59]:
print(a[1] + a[2])

5


In [60]:
#Accesss2-D arrays

In [61]:
print(0,1)#

0 1


In [62]:
#access 3nd element on 1st dimension

In [63]:
print(1,2)

1 2


In [64]:
#Access 3-D arrays

In [65]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [66]:
print(arr[0,1,2])

6


In [67]:
#Negative indexing

In [68]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [69]:
print(arr[1,-1])#access from end

10


# Slicing


In [70]:
#We can pass slice instead if index like [start:end]
#we can also define the step like [start:end:step]

In [71]:
arr=np.array([1,2,3,4,5,6,7])

In [73]:
arr[1:5]#upto not including

array([2, 3, 4, 5])

In [75]:
arr[4:]#from index4 to everything

array([5, 6, 7])

In [76]:
arr[:4]#slice from begenning to index4

array([1, 2, 3, 4])

In [77]:
#Negetive slicing

In [78]:
print(arr[-3:-1])#from (-3+len(arr)) to (-1+len(arr)) index

[5 6]


In [79]:
#step

In [80]:
print(arr[1:5:2])#from index 1 to upto5 with two steps

[2 4]


# Slicing 2-D Arrays

In [81]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [82]:
print(arr[1,1:4])#selecting 1 in first dimension and selecting elements indexed from 1 to upto 4

[7 8 9]


In [83]:
print(arr[0:2,2])#slecting 0 to upto 2 nd index and returing 2 nd indexed element from 2d array

[3 8]


In [84]:
#slicing from both dimensions

In [85]:
print(arr[0:2,1:3])

[[2 3]
 [7 8]]


# Checking the Data Type

In [86]:
print(arr.dtype)

int32


In [87]:
arr2=np.array(["apple","banana","cherry"])

In [88]:
print(arr2.dtype)

<U6


In [89]:
#creating arrays with defined data type

In [90]:
arr3=np.array([1,2,3,4],dtype="S")

In [91]:
print(arr3)

[b'1' b'2' b'3' b'4']


In [92]:
arr4=np.array([1,2,3,4],dtype="i4")#with 4 bytes integer

In [93]:
arr4

array([1, 2, 3, 4])

# Converting Data Types On Existing Arrays

In [94]:
#The best way to change the data type of an existing array is to make copy of an array with astype() method

In [95]:
#The astype() function crreates a copy of the array and allows you to specify the data type

In [96]:
arr =np.array([1.1,2.1,3.1])

In [97]:
newarr=arr.astype("i")

In [98]:
print(arr)

[1.1 2.1 3.1]


In [99]:
print(newarr)

[1 2 3]


In [100]:
print(arr.dtype,newarr.dtype)

float64 int32


In [101]:
#you can use int parameter value

In [103]:
newarr1=arr.astype(int)

In [104]:
print(newarr1)

[1 2 3]


In [105]:
#Change the data type from integer to boolean 

In [106]:
arr=np.array([1,0,3])

In [107]:
newarr=arr.astype(bool)

In [109]:
print(newarr)#if value is >0 then its true either false

[ True False  True]


# Difference between Copy and View

In [110]:
"""
The main difference between copy and view id 
-->copy creates the new array
-->view just views the original array
-->The copy owns the data and any changes made to copy will not affect the original data
and any changes made to original data doesnt effect the copy 
-->The view does not own the data any changes made to view will effect the original one

"""


'\nThe main difference between copy and view id \n-->copy creates the new array\n-->view just views the original array\n-->The copy owns the data and any changes made to copy will not affect the original data\nand any changes made to original data doesnt effect the copy \n-->The view does not own the data any changes made to view will effect the original one\n\n'

In [118]:
#copy
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)
print(x.base)#what is the base of the object x

[42  2  3  4  5]
[1 2 3 4 5]
None


In [117]:
#view
arr1=np.array([1,2,3,4,5])
x=arr1.view()
arr1[0]=42

print(arr1)
print(x)
#make changes
x[1]=8
print(arr1,x)
print(x.base)#what is the base of this object x

[42  2  3  4  5]
[42  2  3  4  5]
[42  8  3  4  5] [42  8  3  4  5]
[42  8  3  4  5]


In [116]:
#to check if array owns the data 
#Every numpy array has the attribute base that returns None if the array owns the data
#otherwise base attribute refers to the original object

# Shape

In [119]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)#The array has 2 dimensions and each dimension has 4 elements 

(2, 4)


In [120]:
#create the array with 5 dimensions using ndim using vector with values 1,2,3,4

In [122]:
arr=np.array([1,2,3,4],ndmin=5)

In [123]:
print(arr)

[[[[[1 2 3 4]]]]]


In [124]:
arr.shape

(1, 1, 1, 1, 4)

In [126]:
arr=np.array([1,2,3,4,5],ndmin=3)

In [127]:
arr.shape

(1, 1, 5)

In [128]:
print(arr)

[[[1 2 3 4 5]]]


In [132]:
arr=np.array([[[1,2,3,4,5,6],[4,5,6,7,8,9]],[[1,2,3,4,5,6],[4,5,6,7,8,9]],[[1,2,3,4,5,6],[4,5,6,7,8,9]]])

In [133]:
print(arr)

[[[1 2 3 4 5 6]
  [4 5 6 7 8 9]]

 [[1 2 3 4 5 6]
  [4 5 6 7 8 9]]

 [[1 2 3 4 5 6]
  [4 5 6 7 8 9]]]


In [134]:
arr.shape

(3, 2, 6)

In [135]:
"""
-->axis-0 value is 3 means we have three 2 dimensional arrays(or someboddy will consider it as 1 st dimension has 3 elements) 
-->axis-1 value is 2 means we have Two 1 dimensional arrays inside each 2 dimension
-->axis-2 value is 6 means we have 6 elements(or six 0 dimensions) in those one dimensional array
"""

'\n-->axis-0 value is 3 means we have three 2 dimensional arrays \n-->axis-1 value is 2 means we have Two 1 dimensional arrays inside each 2 dimension\n-->axis-2 value is 6 means we have 6 elements in those one dimensional array\n'

# Reshaping Arrays

In [136]:
#Reshaping means chaning the shape of an array
#The shape of an array is the numberr of elements in each dimension
#By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [137]:
#Reshape from 1-D to 2-D

In [141]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [142]:
newarr=arr.reshape(4,3)#saying that we want 2 dimensional space whish contains 4 1 dimensional embeded with 3 0 dimensiona;

In [143]:
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [144]:
#Reshape from 1-D to 3-D

In [145]:
newarr1=arr.reshape(2,3,2)#we want 3 dimensional space with contains two 2 dimensional embeded with threee 1 dimensional and further embeded with 2 o dimensional

In [146]:
print(newarr1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [148]:
print(newarr1.base)#so its view

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [149]:
#Unknown Dimension

In [150]:
#you are allowed to have one "Unknown" dimension
#Meaning that you do not have to specify an exact number for one of the dimension in the reshape method
#pass -1 as the value,and the numpy will calculate for you

In [151]:
arr=np.array([1,2,3,4,5,6,7,8])

In [152]:
newarr=arr.reshape(2,2,-1)

In [153]:
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays 

In [154]:
#Flattening array means converting a multidimensional array into a 1D array

In [155]:
#we can use reshape(-1) to dothis

In [156]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [157]:
newarr=arr.reshape(-1)

In [158]:
print(newarr)

[1 2 3 4 5 6]


# Iterating Arrays

In [159]:
#iterating means going throough elements oone by one

In [160]:
#Example

In [161]:
arr=np.array([1,2,3])

In [162]:
for i in arr:
    print(i)

1
2
3


In [163]:
#iterating 2d arrays

In [164]:
arr=np.array([[1,2,3],[4,5,6]])

In [165]:
for x in arr:
    print(x)#iterate through 1 dimensional in the 2 dimensional

[1 2 3]
[4 5 6]


In [166]:
#if w go through n dimensional it will go through n-1th dimensional one by one

In [167]:
for x in arr:
    for y in x:
        print(y)#getting 0 dimensional from 2 dimesional
        #2-0 is 2,so we need 2 for loops to iterate through it

1
2
3
4
5
6


In [168]:
#iterating through 3d arrays

In [169]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [170]:
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [171]:
#3-0 is 3,so we need 3 for loops to get  0 dimensions

In [172]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays using nditer()

In [173]:
#Iterating on each scaler elements 

In [174]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [176]:
arr.shape

(2, 2, 2)

In [177]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


# Iterating Array  with Different Data types

In [178]:
#we can use "op_dtypes" argument and pass it the expected datatype to change the datatype of elements while iterating

In [179]:
"""
-->NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

"""

"\n-->NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].\n\n"

In [180]:
arr =np.array([1,2,3])

In [183]:
for x in np.nditer(arr,flags=["buffered"],op_dtypes=["S"]):
    print(x)#change the data types of the elements while iterating

b'1'
b'2'
b'3'


In [182]:
arr

array([1, 2, 3])

In [184]:
#iterating with different step size

In [185]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [186]:
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [187]:
#enumerated iteration

In [188]:
arr = np.array([1, 2, 3])

In [189]:
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [190]:
#Enumerate on following 2D array's elements:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [191]:
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Numpy Joining Array

In [193]:
#joining means putting the contents of two or more arrays in a single array

In [194]:
#In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

In [195]:
#We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [200]:
arr1=np.array([1, 2, 3])

In [201]:
arr2=np.array([4, 5, 6])

In [202]:
arr=np.concatenate((arr1,arr2))

In [204]:
print(arr)#joined two arrays with one array

[1 2 3 4 5 6]


In [205]:
#join the 2-D arrays along rows(axis=1):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr=np.concatenate((arr1,arr2),axis=1)

In [206]:
print(arr)#2x4

[[1 2 5 6]
 [3 4 7 8]]


In [207]:
arr3=np.concatenate((arr1,arr2),axis=0)

In [208]:
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Joining Arrays Using Stack Functions

In [209]:
#Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [210]:
#We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

In [211]:
#We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [212]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [213]:
arr=np.stack((arr1,arr2),axis=1)

In [214]:
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [215]:
arrc=np.concatenate((arr1,arr2),axis=0)

In [216]:
print(arrc)

[1 2 3 4 5 6]


In [217]:
arr=np.stack((arr1,arr2),axis=0)

In [218]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [219]:
#python provides helper function hstack() to stak along rows

In [220]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [221]:
arr=np.hstack((arr1,arr2))

In [222]:
print(arr)

[1 2 3 4 5 6]


In [223]:
arrv=np.vstack((arr1,arr2))

In [224]:
print(arrv)

[[1 2 3]
 [4 5 6]]
