In [8]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])

In [4]:
print(a)

[1 2 3 4]


In [5]:
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)
tic = time.time()
c=np.dot(a,b)
toc=time.time()
print(c)
print("Vectorized version:"+str(1000*(toc-tic))+"ms")
#non vectorized
c=0
tic =time.time()
for i in range(1000000):
    c +=a[i]*b[i]
toc=time.time()
print(c)
print("For loop:"+ str(1000*(toc-tic))+"ms")

249865.10421672405
Vectorized version:1557.8622817993164ms
249865.1042167133
For loop:730.0386428833008ms


In [6]:
#Both gpu and cpu has simd-->single instruction multiple data

In [7]:
v=[1,2,3,4,6]

In [8]:
u=np.exp(v)

In [9]:
u

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       403.42879349])

In [10]:
#Broadcasting

In [2]:
import numpy as np

In [12]:
A=np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])

In [13]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [14]:
cal =A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [18]:
percentage=100*A/cal.reshape(1,4)

In [19]:
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [17]:
cal.reshape(1,4)

array([[ 59. , 239. , 155.4,  76.9]])

In [20]:
cal.shape

(4,)

In [21]:
cal=cal.reshape(1,4)

In [22]:
cal.shape

(1, 4)

In [24]:
a=np.random.randn(5)

In [25]:
print(a)

[ 0.30462595  0.36947097  0.23599725 -0.05593567  2.1033113 ]


In [26]:
print(a.shape)#one-dimensional has only colums you cannot convert it into the rows 

(5,)


In [27]:
print(a.T)

[ 0.30462595  0.36947097  0.23599725 -0.05593567  2.1033113 ]


In [28]:
print(np.dot(a,a.T))

4.712047703127152


In [29]:
a=np.random.randn(5,1)

In [31]:
a.shape#it is two-dimensional so you can shift it to one dimensiona to another (rows and columns)

(5, 1)

In [32]:
print(a)

[[ 0.16678451]
 [-0.23917821]
 [-0.91973423]
 [-0.12466252]
 [ 0.45348027]]


In [34]:
print(a.T)#because it is the two dimensional you can shift it into the another dimension

[[ 0.16678451 -0.23917821 -0.91973423 -0.12466252  0.45348027]]


In [35]:
print(np.dot(a,a.T))

[[ 0.02781707 -0.03989122 -0.15339743 -0.02079178  0.07563349]
 [-0.03989122  0.05720622  0.21998039  0.02981656 -0.1084626 ]
 [-0.15339743  0.21998039  0.84591105  0.11465638 -0.41708133]
 [-0.02079178  0.02981656  0.11465638  0.01554074 -0.05653199]
 [ 0.07563349 -0.1084626  -0.41708133 -0.05653199  0.20564436]]


In [11]:
x=np.random.rand(32,32,3)

In [12]:
x

array([[[0.98828092, 0.57406754, 0.7892382 ],
        [0.54297214, 0.60204492, 0.1781149 ],
        [0.15091171, 0.43066207, 0.00394988],
        ...,
        [0.96558262, 0.93524075, 0.10923999],
        [0.4009862 , 0.85810287, 0.78256833],
        [0.92440738, 0.98752198, 0.32023646]],

       [[0.01441656, 0.3392348 , 0.70416558],
        [0.49079317, 0.40193778, 0.88857452],
        [0.56930065, 0.77132487, 0.7487313 ],
        ...,
        [0.15688835, 0.74021687, 0.69448091],
        [0.29619254, 0.53905715, 0.16372248],
        [0.69015959, 0.19328925, 0.62318028]],

       [[0.95316986, 0.33899759, 0.8363011 ],
        [0.56837746, 0.49380254, 0.37069302],
        [0.55941871, 0.7612918 , 0.14894995],
        ...,
        [0.90363577, 0.04765889, 0.70188027],
        [0.46356205, 0.53460502, 0.81244575],
        [0.90583547, 0.00139583, 0.11672581]],

       ...,

       [[0.44344393, 0.48395805, 0.13153564],
        [0.05668791, 0.95923564, 0.89134004],
        [0.09097428, 0

In [15]:
x.shape

(32, 32, 3)

In [21]:
x[0,2,1]

0.4306620681981642

In [24]:
x=x.reshape((32*32*3,1))

In [25]:
x

array([[0.98828092],
       [0.57406754],
       [0.7892382 ],
       ...,
       [0.45081688],
       [0.46878417],
       [0.94430457]])

In [26]:
a=np.random.randn(2,3)

In [27]:
b=np.random.randn(2,1)

In [28]:
c=a+b

In [29]:
a.shape

(2, 3)

In [30]:
b.shape

(2, 1)

In [31]:
c.shape

(2, 3)

In [32]:
c

array([[0.08524286, 0.43476573, 1.14466211],
       [1.71295006, 1.19563695, 0.46289819]])

In [33]:
b

array([[0.43010349],
       [0.03287414]])

In [34]:
a

array([[-0.34486062,  0.00466224,  0.71455862],
       [ 1.68007592,  1.16276281,  0.43002405]])

In [35]:
a=np.random.randn(4,3)

In [36]:
b=np.random.randn(3,2)

In [37]:
a

array([[-0.37465219, -0.64055628,  0.06251339],
       [-0.42418261,  0.81399464,  1.72949096],
       [ 0.42097206, -2.43600508, -2.07639671],
       [-1.55615199, -0.42088111,  0.11056957]])

In [38]:
b

array([[ 0.21546429, -1.7419393 ],
       [ 0.23907471, -0.43691083],
       [ 1.19132848,  0.69834172]])

In [41]:
c=a*b#element wise multiplication

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [42]:
a = np.random.randn(12288, 150)

In [43]:
b = np.random.randn(150, 45)

In [44]:
c=np.dot(a,b)

In [45]:
c.shape

(12288, 45)

In [59]:
a=np.random.rand(3,4)

In [60]:
b=np.random.rand(4,1)

In [61]:
a

array([[0.15467146, 0.44251925, 0.48143923, 0.33110369],
       [0.44147019, 0.77678545, 0.12347317, 0.19056626],
       [0.84263622, 0.86246068, 0.8619811 , 0.19000886]])

In [62]:
b

array([[0.83900217],
       [0.96828998],
       [0.79829955],
       [0.3687455 ]])

In [63]:
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [64]:
a+b.T

array([[0.99367364, 1.41080922, 1.27973878, 0.69984919],
       [1.28047237, 1.74507543, 0.92177272, 0.55931176],
       [1.6816384 , 1.83075066, 1.66028065, 0.55875436]])

In [65]:
a=np.random.randn(3,3)

In [66]:
b=np.random.randn(3,1)

In [67]:
a

array([[-0.4214776 ,  1.18020589,  0.20980409],
       [-1.81848586, -0.45249661, -0.12570968],
       [ 0.17917337,  0.12441999, -1.22958977]])

In [68]:
b

array([[-1.72603927],
       [ 0.20206781],
       [ 0.13728449]])

In [69]:
c=a*b

In [70]:
c

array([[ 0.7274869 , -2.03708172, -0.3621301 ],
       [-0.36745746, -0.091435  , -0.02540188],
       [ 0.02459773,  0.01708093, -0.1688036 ]])

In [71]:
c.shape

(3, 3)

In [72]:
u=1*2

In [73]:
v=1*3

In [74]:
w=2+3

In [75]:
j=u+v-w

In [76]:
j

0

In [77]:
t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])

In [78]:
t_image.shape

(3, 3, 2)

In [80]:
v=t_image.reshape(3*3*2,1)

In [81]:
v

array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551],
       [0.92814219],
       [0.96677647],
       [0.85304703],
       [0.52351845],
       [0.19981397],
       [0.27417313],
       [0.60659855],
       [0.00533165],
       [0.10820313],
       [0.49978937],
       [0.34144279],
       [0.94630077]])

In [82]:
v.shape

(18, 1)

In [83]:
vt=t_image.reshape(3*3*2,1)

In [84]:
vt

array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551],
       [0.92814219],
       [0.96677647],
       [0.85304703],
       [0.52351845],
       [0.19981397],
       [0.27417313],
       [0.60659855],
       [0.00533165],
       [0.10820313],
       [0.49978937],
       [0.34144279],
       [0.94630077]])

In [85]:
vt.shape

(18, 1)

In [86]:
#Normalizing rows

In [91]:
x=np.array([[0,3,4],[2,6,4]])

In [92]:
y=np.array([[5],[56]])

In [93]:
y

array([[ 5],
       [56]])

In [94]:
y.shape

(2, 1)

In [95]:
x.shape

(2, 3)

In [97]:
x_norm= np.linalg.norm(x,axis=1,keepdims=True)

In [98]:
x_norm

array([[5.        ],
       [7.48331477]])

In [103]:
np.sqrt(3**2+4**2)#norm of 1 st dimension in X

5.0

In [104]:
x_nom=x/(x_norm)

In [105]:
x_nom

array([[0.        , 0.6       , 0.8       ],
       [0.26726124, 0.80178373, 0.53452248]])

In [106]:
#X_norm has the same number of rows as X and has only one column

In [108]:
#softmax-->is the normalizing function in numpy.

In [109]:
#softmax(x)-->[softmax(first_row of x),softmax(second row of x).....softmax(last row of x)]

In [110]:
#softmax can be performed on columns also

In [111]:
#each feature will be in its row

In [112]:
#each training example is in its own column

In [3]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0

for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1), len(x2))) # we create a len(x1)*len(x2) matrix with only zeros

for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i] * x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))

for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.0ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
 ---

In [4]:
dot

278

In [5]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

dot = 0

for i in range(len(x1)):
    dot += x1[i] * x2[i]

In [8]:
dot

278

In [11]:
x=np.array([81.,18.,18.,81.,0.,81.,18.,45. ,0. ,0.,81.,18.,45.,0.,0.])

In [12]:
x

array([81., 18., 18., 81.,  0., 81., 18., 45.,  0.,  0., 81., 18., 45.,
        0.,  0.])

In [15]:
x.sum()

486.0

In [16]:
x1

[9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]

In [17]:
x2

[9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

In [22]:
k =np.zeros((len(x1),len(x2)))

In [23]:
k

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [24]:
len(x1)

15

In [26]:
k.shape

(15, 15)

In [ ]:
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()

In [27]:
o=np.random.rand(3,len(x1))

In [28]:
o.shape

(3, 15)

In [29]:
gdot=np.zeros(o.shape[0])

In [30]:
gdot.shape

(3,)

In [31]:
o

array([[0.93031673, 0.53005575, 0.97611802, 0.49516568, 0.47452127,
        0.50682777, 0.3992611 , 0.11877825, 0.62218798, 0.64241268,
        0.45412212, 0.25559879, 0.54151842, 0.32574864, 0.11316489],
       [0.01418317, 0.63912453, 0.83768736, 0.28040454, 0.73580443,
        0.20117072, 0.83426709, 0.22943429, 0.06143121, 0.32811207,
        0.78119018, 0.8047759 , 0.15004745, 0.5343548 , 0.9190249 ],
       [0.7976218 , 0.2485071 , 0.0340727 , 0.00866329, 0.60562752,
        0.72947608, 0.59507702, 0.14918194, 0.23189873, 0.44119095,
        0.98046165, 0.36121297, 0.74739472, 0.34485051, 0.13261404]])

In [32]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

In [34]:
yhat.shape

(5,)

In [35]:
y.shape

(5,)

In [39]:
np.abs(y)-np.abs(yhat)

array([ 0.1, -0.2, -0.1,  0.6,  0.1])

In [40]:
np.abs(y)

array([1, 0, 0, 1, 1])

In [42]:
abs(y-yhat)

array([0.1, 0.2, 0.1, 0.6, 0.1])